{% set name = "sphinx-confluence" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Arello-Mobile/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0a81df5cb46e6357274db58dbc38f407ca075a0dc3cdf7d2a8341a0d8a743461

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sphinx >=1.3.5
    - docutils ==0.12

test:
  imports:
    - sphinx_confluence

about:
  home: https://github.com/Arello-Mobile/sphinx-confluence
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sphinx extension for making the documentation compatible with the Confluence Storage Format.

  description: |
    This extension is written as part of our Documentation Toolkit which
    we use in our job daily. The main idea of toolkit is to make a process
    of creating and updating documentation able to be automated.
  doc_url: https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html
  dev_url: https://github.com/Arello-Mobile/sphinx-confluence

extra:
  recipe-maintainers:
    - CurtLH
